blog/accounts/urls.py
from django.urls import path
from django.conf.urls import url
from django .contrib import admin
from django.contrib.auth import views as auth_views

from .views import SignUp,change_password

app_name = 'accounts'
urlpatterns = [
    path('login/', auth_views.login,{"template_name":"login.html"}, name="login"),
    path('logout/', auth_views.logout,{"template_name":"logout.html"}, name="logout"),
    path('signup/', SignUp.as_view(), name='signup'),
    path('password/', change_password, name='change_password'),
    
    
    path(
        'password_reset/', 
        auth_views.password_reset,
        {
            "template_name":"password_reset_form.html",
            "subject_template_name":"password_reset_subject.txt"
            
        }, 
        name='password_reset'),
    
    path('password_reset/done', auth_views.password_reset_done,{"template_name":"password_reset_done.html"}, name="password_reset_done"),
    
    path('reset/<uidb64>/<token>/', auth_views.password_reset_confirm,{'template_name':'password_reset_confirm.html'},name="password_reset_confirm"),
    path('reset/done/', auth_views.password_reset_complete, {'template_name':'password_reset_complete.html'},name="password_reset_complete")
    
]

blog/blog/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include("posts.urls", namespace="posts")),
    
    path('accounts/', include("accounts.urls")),
    path('accounts/',include('django.contrib.auth.urls')),
]

if settings.DEBUG :
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/posts/urls.py
from django.urls import path
from .views import (
    post_detail,
    post_list,
    post_delete,
    post_create,
    PostLikeToggle,
    PostList,
    PostDetail
)

app_name = "posts"
urlpatterns = [
    path('', post_list, name="list"),
    path('<int:id>/', post_detail, name="detail"),
    path('<int:id>/like', PostLikeToggle.as_view(), name="like-toggle"),
    path('<int:id>/delete/', post_delete, name="delete"),
    path('create/', post_create, name="create"),
    path('api/',PostList.as_view()),
    path('api/<int:pk>', PostDetail.as_view())
]

blog/accounts/models.py
from django.db import models

# Create your models here.

blog/posts/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.conf import settings

from markdown_deux import markdown


def upload_location(instance,filename):
    return 'user_%s/%s'%(instance.id, filename)

    
# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=255)


    def __str__(self):
        return self.title

    class Meta: 
        verbose_name_plural = "Categories"


class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False , auto_now=True)
    
    image = models.ImageField(upload_to = upload_location, blank=True, null=True)
    category = models.ForeignKey(Category,on_delete=models.CASCADE,default="")

    #likes here related to user by many to many relationship
    likes = models.ManyToManyField(User, blank=True ,related_name="post_likes")
   
    def __str__(self):
        return self.title


    def get_absolute_url(self):
        #return the absolute url of the post
        return reverse("posts:detail", kwargs={"id":self.id})

    def get_like_url(self):
        # retutn page post likes
        return reverse("posts:like-toggle", kwargs={"id":self.id})

    def get_markdown(self):
        content = self.content
        #return marked down content
        return markdown(content)

blog/posts/forms.py
from django import forms
from django.forms import ModelForm
from pagedown.widgets import PagedownWidget

from .models import Post


class PostForm(ModelForm):
    # add pagedown to content text field
    content = forms.CharField(widget=PagedownWidget())
    class Meta:
        model = Post 
        fields = [
            "title",
            "content",
            "image",
            "category",
        
        ]

blog/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.urls import reverse_lazy
from django.views import generic



# Create your views here.


class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('accounts:login')
    template_name = 'signup.html'


def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)

        if form.is_valid():
            user = form.save()
            #update hash for the current session
            update_session_auth_hash(request,user)
            return redirect("accounts:change_password")
    else :
        form = PasswordChangeForm(request.user)

    context= {
        "form":form,
    }

    return render(request,"change_password.html", context)

blog/posts/views.py
from django.shortcuts import render,get_object_or_404, redirect
from django.http import (
    HttpResponse, 
    HttpResponseRedirect,
    Http404
)
from django.db.models import Q

from django.views.generic import RedirectView

from rest_framework.generics import (
    ListAPIView,
    RetrieveUpdateDestroyAPIView
)
from .models import Post
from .forms import PostForm
from .serializers import PostSerializer

# Create your views here.

def post_list(request):
    posts = Post.objects.all()

    #searching the post by title,content,username and category
    query = request.GET.get('q')

    if query :
        posts = posts.filter(
            Q(title__icontains=query)|
            Q(content__icontains=query)|
            Q(user__username__icontains=query)|
            Q(category__title__icontains=query)
            
        ).distinct()
    context = {
        "posts": posts,
    }

    return render(request, "post_list.html", context)

def post_detail(request, id=None):
    post = get_object_or_404(Post, id=id)
    
    context = {
        "post": post,
    }

    return render(request, "post_detail.html", context)

def post_create(request):
    
    if request.method == "POST":
        form = PostForm(request.POST or None, request.FILES or None)

        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()

            return HttpResponseRedirect(post.get_absolute_url())
    else :
        form = PostForm()
    context = {
        "form":form,
    }

    return render(request,"post_form.html", context)

def post_delete(request, id=None):
    post = get_object_or_404(Post, id=id)
    
    #checking if user is superuser
    if not request.user.is_staff or not request.user.is_authenticated:
        raise Http404
    post.delete()

    return redirect("posts:list")

class PostLikeToggle(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        #get the id and search the post by id
        id = self.kwargs.get("id")
        post = get_object_or_404(Post, id=id)
        url_ = post.get_absolute_url()
        user = self.request.user
        #if user in likes then remove him if not add him
        if user.is_authenticated:
            if user in post.likes.all():
                post.likes.remove(user)
            else:
                post.likes.add(user)

        return url_


#code for api list, retriebe, update and destroy view
class PostList(ListAPIView):
    queryset = Post.objects.all()
    serializer_class = PostSerializer

class PostDetail(RetrieveUpdateDestroyAPIView):
    queryset = Post.objects.all()
    serializer_class = PostSerializer

blog/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}Django Blog{% endblock title %}</title>
        {{ form.media }}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    </head>

    <body>
        {% include 'navbar.html' %}
        {% block content %}
            
        {% endblock content %}
        

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    </body>
</html>

blog/templates/change_password.html
{% extends 'base.html' %}


{% block title %}{{ block.super }} | Change Password{% endblock title %}
    


{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save Changes</button>
    </form>
{% endblock content %}
    

blog/templates/login.html
{% extends 'base.html' %}

{% block title %}{{ block.super }} | login{% endblock title %}


{% block content %}
    <h2>Login</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <p><a href="{% url 'accounts:password_reset' %}">Forgot your password ?</a></p>
        <button type="submit">Login</button>
    </form>
    
{% endblock content %}
    

blog/templates/logout.html
{% extends 'base.html' %}

{% block title %}{{ block.super }} | logout{% endblock title %}


{% block content %}
    <h2>you logged out successfully, come back again</h1>
{% endblock content %}
    

blog/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light" role="navigation">
    <div class="container">
        <a class="navbar-brand" href="{% url 'posts:list' %}">Django Blogs</a>
        <button class="navbar-toggler border-0" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar">
            &#9776;
        </button>
        <div class="collapse navbar-collapse" id="exCollapsingNavbar">
            <ul class="nav navbar-nav">
                
                {% if request.user.is_authenticated and user.is_staff %}
                    <li class="nav-item"><a href="{% url 'posts:create' %}" class="nav-link">Create</a></li>
                {% endif %}
                <!-- <li class="nav-item"><a href="#" class="nav-link">Link</a></li>-->
                <!--<li class="nav-item"><a href="#" class="nav-link">Service</a></li>-->
                <!-- <li class="nav-item"><a href="#" class="nav-link">More</a></li> -->
            </ul>
            
            <form method="GET" action="" class="form-inline my-2 my-lg-0">
                <input type="text" class="form-control mr-sm-2" type="search" aria-label="Search" name="q" placeholder="Search posts" value="{{ request.get.q}}">
                <input class="btn btn-outline-success my-2 my-sm-0" type="submit" value="Search">
            </form>
            {% if not request.user.is_authenticated and not "/accounts/login/" in request.get_full_path %}
                <ul class="nav navbar-nav flex-row justify-content-between ml-auto">
                    <li class="nav-item order-2 order-md-1"><a href="#" class="nav-link" title="settings"><i class="fa fa-cog fa-fw fa-lg"></i></a></li>
                    <li class="dropdown order-1">
                        <button type="button" id="dropdownMenu1" data-toggle="dropdown" class="btn btn-outline-secondary dropdown-toggle">Admin <span class="caret"></span></button>
                        <ul class="dropdown-menu dropdown-menu-right mt-2">
                            <li class="px-3 py-2">
                                <a href="{% url 'accounts:login' %}">Login</a>
                            </li>
                            <li class="px-3 py-2">
                                <a href="{% url 'accounts:signup' %}">Sign Up</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            {% endif %}

            {% if  request.user.is_authenticated  %}
                <ul class="nav navbar-nav flex-row justify-content-between ml-auto">
                    <li class="nav-item order-2 order-md-1"><a href="#" class="nav-link" title="settings"><i class="fa fa-cog fa-fw fa-lg"></i></a></li>
                    <li class="dropdown order-1">
                        <button type="button" id="dropdownMenu1" data-toggle="dropdown" class="btn btn-outline-secondary dropdown-toggle">Admin <span class="caret"></span></button>
                        <ul class="dropdown-menu dropdown-menu-right mt-2">
                            <li class="px-3 py-2">
                                <a href="{% url 'accounts:logout' %}">Logout</a>
                            </li>
                            
                            <li class="px-3 py-2">
                                <a href="{% url 'accounts:change_password' %}">Change password</a>
                            </li>
                            
                            <li class="px-3 py-2">
                                <a href="{% url 'accounts:password_reset' %}">Reset Password</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            {% endif %}

            
        </div>
    </div>
</nav>

blog/templates/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}
    <p>
        Your password has been set. You may go ahead and <a href="{% url 'accounts:login' %}">sign in</a> now.
    </p>
{% endblock content %}

blog/templates/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}
    {% if validlink %}
        <h3>Change password</h3>
        <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Change password</button>
        </form>
    {% else %}
        <p>
        The password reset link was invalid, possibly because it has already been used.
        Please request a new password reset.
        </p>
    {% endif %}
{% endblock content %}

blog/templates/password_reset_done.html
{% extends 'base.html' %}

{% block content %}
    <p>
        We've emailed you instructions for setting your password, if an account exists with the email you entered.
        You should receive them shortly.
    </p>
    <p>
        If you don't receive an email, please make sure you've entered the address you registered with,
        and check your spam folder.
    </p>
{% endblock content %}

blog/templates/password_reset_email.html
{% autoescape off %}
    To initiate the password reset process for your {{ user.get_username }} TestSite Account,
    click the link below:

    {{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

    If clicking the link above doesn't work, please copy and paste the URL in a new browser
    window instead.

    Sincerely,
    The TestSite Team
{% endautoescape %}

blog/templates/password_reset_form.html
{% extends 'base.html' %} 

{% block content %}
    <h3>Forgot password</h3>

    <form method="post">
        {% csrf_token %} {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
{% endblock content %}

blog/templates/post_detail.html
{% extends 'base.html' %}
{% load markdown_deux_tags %}

{% block content %}
    <h1>{{ post.title }} </h1><br>
    <img src="{{ post.image.url }}">
    {{ post.get_markdown | safe | linebreaks }}<br>
    {{ post.timestamp }}<br>
    {{ post.updated }}<br>
    {{ post.category.title }}<br>
    {{ post.user }}

    <p>Likes : {{ post.likes.count }} <a href="{{ post.get_like_url }}">Like</a></p>
{% endblock content %}
    

blog/templates/post_form.html
{% extends 'base.html' %}


{% block content %}
    <h1>form</h1>
    <form method="POST" action="." enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create Post</button>
    </form>
    
{% endblock content %}

blog/templates/post_list.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
		{% for post in posts %}
			<div class="row">
	  			<div class="col-sm-12">
	    			<div class="thumbnail">
	    				{% if post.image %}
	    					<img src="{{ post.image.url }}" class="img-responsive">
	    				{% endif %}
	      				<div class="caption">
								

	        				<h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a> <small>{{ post.timestamp}}</small><b style="color:red;">{{ post.category }}</b></h3>

	        				<p>{{ post.content | linebreaks | truncatechars:120 }}</p>
	        				<p><a href="{{ post.get_absolute_url }}" class="btn btn-primary" role="button">View</a></p>			
	      				</div>
		    		</div>
	  			</div>
	  			<hr>
	  		</div>
		{% endfor %}
    </div>
{% endblock content %}

blog/templates/signup.html
{% extends 'base.html' %}

{% block title %}{{ block.super }} | Sign Up{% endblock title %}


{% block content %}
    <h2>Sign Up</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Sign up</button>
    </form>
{% endblock content %}
    
    